---
exclude: (?x)^( includes/)$
repos:
  # Several miscellaneous checks and fix (on yaml files, end of files fix)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # This hook tests the name of the branch and return an error if the name is
      #  'develop' or an official version 'x.y'
      # So you can't commit if your branch name is not a custom branch name.
      # Using a custom branch name is good practice that makes it easier to manage PRs.
      # You can skip this:
      #  - Permanently:
      #      export SKIP=no-commit-to-branch   # In your .bashrc or session.
      #  - Only this for one commit:
      #      SKIP=no-commit-to-branch git commit -a -m "My message"
      #  - Skipping all checks for a commit:
      #      git commit -a -m "My message" --no-verify
      #      (Recommendation: run git commit -a .. once, then with `--no-verify`)
      # This checks that xml files are correct
      - id: check-xml
      # This checks that yaml files are correct
      - id: check-yaml
        args: [--unsafe]
      # This checks that json files are correct
      - id: check-json
      # Fixes Fix files that have DOS end of line endings
      - id: mixed-line-ending
        # alternative for dev/tools/fixdosfiles.sh
        args: [--fix=lf]
      # Remove trailing whitespace
      - id: trailing-whitespace
        exclude_types: [markdown]
      # Fix the end of file
      - id: end-of-file-fixer
      # Check that there are no completely merged file conflicts
      - id: check-merge-conflict
        stages: [pre-commit, pre-rebase, pre-commit, pre-merge-commit]
      # Fix the first UTF8 byte
      - id: fix-byte-order-marker
      # Check that there are no files that have are the same when uppercased (conflict on windows)
      - id: check-case-conflict

  # Beautify shell scripts
  - repo: https://github.com/lovesegfault/beautysh.git
    rev: v6.2.1
    hooks:
      - id: beautysh
        exclude: |
          (?x)^(dev/setup/git/hooks/pre-commit
               )$
        args: [--tab]

  # Run local script
  #
  # For example, to update the license in edited files, you could add to local.sh:
  #
  #   ```shell
  #   #!/bin/bash
  #   MYDIR=$(dirname "$0")
  #   git diff HEAD --name-only | grep -v includes | \
  #       xargs "$MYDIR/dev/tools/updatelicense.php"
  #   ```
  - repo: local
    hooks:
      - id: local-precommit-script
        name: Run local script before commit if it exists
        language: system
        entry: bash -c '[ ! -x local.sh ] || ./local.sh'
        pass_filenames: false
      - id: duplicate-lang-lines
        stages: [manual]
        name: Find duplicate language lines
        files: (?x)^(langs/fr_FR/.*\.lang)
        language: script
        entry: ../../dev/tools/fixduplicatelanglines.sh
        pass_filenames: false
        args: [list]
      - id: duplicate-lang-keys
        stages: [manual]
        name: Find duplicate language keys
        files: (?x)^(langs/fr_FR/.*\.lang)
        language: script
        entry: ../../dev/tools/fixduplicatelangkey.sh
        pass_filenames: false
        args: [list]

  # Check PHP syntax
  - repo: https://github.com/mdeweerd/pre-commit-php
    rev: v1.6.8
    hooks:
      - id: php-cbf
        files: \.(php)$
        args: [--standard=../../../dev/setup/codesniffer/ruleset.xml]
      - id: php-cs
        files: \.(php)$
        args:
          [
            --standard=../../../dev/setup/codesniffer/ruleset.xml,
            --report=emacs,
            --severity=5,
            --no-colors,
          ]
      - id: php-lint
      - id: php-stan
        stages: [manual]
        files: \.(php)$

  # Prettier (format code, only for non common files)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        stages: [manual]
        exclude:
          (?x)^( .*\.(phar |min\.css |lock) | (includes|theme/common)/.*
          )$
        exclude_types:
          - php
          - executable
          - binary
          - shell
          - javascript
          - markdown
          - html
          - less
          - plain-text
          - scss
          - css
          - yaml

  # Check format of yaml files
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
        args:
          - --no-warnings
          - -d
          - "{extends: relaxed, rules: {line-length: {max: 120}}}"

  # Check some shell scripts
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        args: [-W, "100"]

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.4
    hooks:
      - id: sqlfluff-lint
        stages: [pre-commit, manual]  # manual needed for ci
        exclude: (?x)^
          (includes/.*
          |install/doctemplates/websites/.*_template
          |install/doctemplates/websites/website_template-.*\.sql
          )$
